ALTER TABLE CUSTOMER
DROP CONSTRAINT ADDRESS_FK;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CUSTOMER;


CREATE TABLE ADDRESS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  STREET_NAME VARCHAR(250),
  CITY VARCHAR(250)
);

CREATE TABLE CUSTOMER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250),
  LAST_NAME VARCHAR(250),
  AGE INT(3),
  ADDRESS_ID INT(11) NOT NULL,
  CONSTRAINT ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS (ID)
);


COMMIT;